[core.template]
unit = "S7-200"
vendor = "Siemens"
description = "Rough simulation of a basic Siemens S7-200 CPU with 2 slaves"
protocols = ["HTTP", "MODBUS", "s7comm", "SNMP"]
creator = "the conpot team"

[core.databus.key_value_mappings]
FacilityName = "Mouser Factory"
SystemName = "Technodrome"
SystemDescription = "Siemens, SIMATIC, S7-200"
Uptime = "conpot.emulators.misc.uptime.Uptime"
sysObjectID = "0.0"
sysContact = "Siemens AG"
sysName = "CP 443-1 EX40"
sysLocation = "Venus"
sysServices = "72"
memoryModbusSlave0BlockA = "[random.randint(0,1) for b in range(0,128)]"
memoryModbusSlave0BlockB = "[random.randint(0,1) for b in range(0,32)]"
memoryModbusSlave255BlockA = "[random.randint(0,1) for b in range(0,128)]"
memoryModbusSlave255BlockB = "[random.randint(0,1) for b in range(0,32)]"
memoryModbusSlave1BlockA = "[random.randint(0,1) for b in range(0,128)]"
memoryModbusSlave1BlockB = "[random.randint(0,1) for b in range(0,32)]"
memoryModbusSlave2BlockC = "[random.randint(0,1) for b in range(0,8)]"
memoryModbusSlave2BlockD = "[0 for b in range(0,32)]"
Copyright = "Original Siemens Equipment"
s7_id = "88111222"
s7_module_type = "IM151-8 PN/DP CPU"
empty = ""
